# Generated by Django 5.1.4 on 2024-12-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaiapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="description",
            field=models.TextField(default=" "),
        ),
        migrations.AddField(
            model_name="chaivariety",
            name="name",
            field=models.CharField(default=" ", max_length=100),
        ),
    ]
